apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: example-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: example-voting-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: example-voting-app
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        ports:
         - containerPort: 5432
         
---

apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-service
    app: example-voting-app
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgres-pod
    app: example-voting-app
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: example-voting-app
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: example-voting-app
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        
---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: example-voting-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: example-voting-app
    
    

apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: example-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: result-app-pod
      app: example-voting-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: example-voting-app
    spec:
      containers:
      - name: result-app
        image: plmnko098/result-app
        ports:
        - containerPort: 80
        
 ---
 
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: example-voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: result-app-pod
    app: example-voting-app
    
---
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: example-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: voting-app-pod
      app: example-voting-app
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: example-voting-app
    spec:
      containers:
      - name: voting-app
        image: plmnko098/voter-app
        ports:
        - containerPort: 80
        
 --- 
 
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: example-voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: voting-app-pod
    app: example-voting-app
    
 ---
 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: example-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app: example-voting-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: example-voting-app
    spec:
      containers:
      - name: worker-app
        image: plmnko098/worker-app
 
 

